terraform exit

diff --git a/terraform/createstate b/terraform/createstate
--- a/terraform/createstate
+++ b/terraform/createstate
@@ -30,4 +30,10 @@ terraform {
 }
 _END_
 
-terraform apply -auto-approve
+if terraform apply -auto-approve
+then
+  echo "SUCCESS"
+else
+  echo "FAILURE"
+  exit 1
+fi
